In [50]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
sns.set()

Reading The Data Set

In [51]:
df = pd.read_csv('Corona_NLP.csv', encoding='latin1')

In [52]:
df.head()

UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

Removing Nulls And Duplicates

In [53]:
df.drop_duplicates(subset='OriginalTweet',inplace=True)

In [54]:
df.isnull().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [55]:
df = df.dropna(axis = 0)

In [56]:
df.isnull().sum()

UserName         0
ScreenName       0
Location         0
TweetAt          0
OriginalTweet    0
Sentiment        0
dtype: int64

In [57]:
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [58]:
sw = stopwords.words('English')
print(sw)
lm = WordNetLemmatizer()

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [59]:
df.shape

(32567, 6)

In [60]:
df.duplicated().sum()

0

In [61]:
df.reset_index(drop=True, inplace=True)


In [62]:
df['OriginalTweet'][12]

'Lines at the grocery store have been unpredictable, but is eating out a safe alternative? \r\r\n\r\r\nFind out more about whether you should be avoiding restaurants right now:  https://t.co/9idZSis5oQ\r\r\n\r\r\n#coronavirus #covid19 https://t.co/ZHbh898lf6'

In [63]:
df1  = df.copy()
df1.shape

(32567, 6)

Preprocess the Covid tweets based on the following parameter:
a) Tokenizing words
b) Convert words to lower case
c) Removing Punctuations
d) Removing Stop words
e) Stemming or lemmatizing the words

In [64]:
res = []
for i in df['OriginalTweet']:
    t = re.sub('(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)|([^0-9A-Za-z t])|(w+://S+)',' ',i)
    t = t.lower()
    t = word_tokenize(t)
    t = [i for i in t if i not in sw]
    t = [lm.lemmatize(i) for i in t]
    t = " ".join(t)
    res.append(t)
print(res)

['gahan http co ifz9fan2pa http co xx6ghgfzcc http co i2nlzdxno8', 'advice talk neighbour family exchange phone number create contact list phone number neighbour school employer chemist gp set online shopping account po adequate supply regular med order', 'coronavirus australia woolworth give elderly disabled dedicated shopping hour amid covid 19 outbreak http co binca9vp8p', 'news region first confirmed covid 19 case came sullivan county last week people flocked area store purchase cleaning supply hand sanitizer food toilet paper good dodson report http co cfxch7a2lu', 'cashier grocery store sharing insight 19 prove credibility commented civics class know talking http co iefdnehgdo', 'supermarket today buy toilet paper 19 http co evxkqlidaz', 'due covid 19 retail store classroom atlanta open walk business class next two week beginning monday march 16 continue process online phone order normal thank understanding http co kw91zj5o5i', 'corona prevention stop buy thing cash use online pa

In [65]:
df1

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3804       48756     ÜT: 36.319708,-82.363649  16-03-2020   
4          3805       48757          35.926541,-78.753267  16-03-2020   
...         ...         ...                           ...         ...   
32562     44946       89898                  Brooklyn, NY  14-04-2020   
32563     44948       89900              Toronto, Ontario  14-04-2020   
32564     44949       89901                          OHIO  14-04-2020   
32565     44951       89903  Wellington City, New Zealand  14-04-2020   
32566     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral  
1      advice Talk to your neighbours family to excha...  Positive  
2      Coronavirus Australia: Woolworths to give elde...  Positive  
3      As news of the region’s first confirmed COVID...  Positive  
4      Cashier at grocery store was sharing his insig...  Positive  
...                                                  ...       ...  
32562  Y’all really shitting that much more at home?...  Negative  
32563  Still shocked by the number of #Toronto superm...  Negative  
32564  I never that we’d be in a situation &amp; wor...  Positive  
32565  Airline pilots offering to stock supermarket s...   Neutral  
32566  @TartiiCat Well new/used Rift S are going for ...  Negative  

[32567 rows x 6 columns]

Convert the 'Extremely Positive' and 'Extremely Negative' Sentiments to 'Positive' and
'Negative' sentiments respectively

In [66]:
for index, row in df.iterrows():
    if df.loc[index, 'Sentiment'] == 'Extremely Positive':
        df['Sentiment'][index] = 'Positive'
    if df.loc[index, 'Sentiment'] == 'Extremely Negative':
        df['Sentiment'][index] = 'Negative'

    

C:\Users\mohit\AppData\Local\Temp/ipykernel_6976/699492029.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sentiment'][index] = 'Positive'
C:\Users\mohit\AppData\Local\Temp/ipykernel_6976/699492029.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sentiment'][index] = 'Negative'


In [67]:
df

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3804       48756     ÜT: 36.319708,-82.363649  16-03-2020   
4          3805       48757          35.926541,-78.753267  16-03-2020   
...         ...         ...                           ...         ...   
32562     44946       89898                  Brooklyn, NY  14-04-2020   
32563     44948       89900              Toronto, Ontario  14-04-2020   
32564     44949       89901                          OHIO  14-04-2020   
32565     44951       89903  Wellington City, New Zealand  14-04-2020   
32566     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral  
1      advice Talk to your neighbours family to excha...  Positive  
2      Coronavirus Australia: Woolworths to give elde...  Positive  
3      As news of the region’s first confirmed COVID...  Positive  
4      Cashier at grocery store was sharing his insig...  Positive  
...                                                  ...       ...  
32562  Y’all really shitting that much more at home?...  Negative  
32563  Still shocked by the number of #Toronto superm...  Negative  
32564  I never that we’d be in a situation &amp; wor...  Positive  
32565  Airline pilots offering to stock supermarket s...   Neutral  
32566  @TartiiCat Well new/used Rift S are going for ...  Negative  

[32567 rows x 6 columns]

Transform the words into vectors using TF-IDF Vectorizer

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [69]:
tf = TfidfVectorizer(max_features=1500)
r3 = tf.fit_transform(res).todense()
print(len(tf.get_feature_names_out()))

1500


In [70]:
x = r3
y = df['Sentiment']
print(type(x))
print(type(y))

<class 'numpy.matrix'>
<class 'pandas.core.series.Series'>


Split data into training and test data.

In [71]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24425, 1500)
(8142, 1500)
(24425,)
(8142,)


Multinomial Naïve Bayes Classification

In [72]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB

In [73]:
m1 = MultinomialNB()
m1.fit(x_train, y_train)

c:\Users\mohit\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


MultinomialNB()

In [74]:
print('Training Score',m1.score(x_train, y_train))
print('Testing Score',m1.score(x_test, y_test))

c:\Users\mohit\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Training Score 0.6910951893551689
Testing Score 0.6581920903954802


c:\Users\mohit\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [75]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

['Negative' 'Positive' 'Negative' ... 'Positive' 'Positive' 'Positive']


c:\Users\mohit\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Compute Confusion matrix and classification report for each of these models


In [76]:
from sklearn.metrics import confusion_matrix, classification_report

In [77]:
cm_m1 = confusion_matrix(y_test, ypred_m1)
print(cm_m1)
print(classification_report(y_test, ypred_m1))

[[2028   59  892]
 [ 380  306  850]
 [ 531   71 3025]]
              precision    recall  f1-score   support

    Negative       0.69      0.68      0.69      2979
     Neutral       0.70      0.20      0.31      1536
    Positive       0.63      0.83      0.72      3627

    accuracy                           0.66      8142
   macro avg       0.68      0.57      0.57      8142
weighted avg       0.67      0.66      0.63      8142



In [78]:
df

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3804       48756     ÜT: 36.319708,-82.363649  16-03-2020   
4          3805       48757          35.926541,-78.753267  16-03-2020   
...         ...         ...                           ...         ...   
32562     44946       89898                  Brooklyn, NY  14-04-2020   
32563     44948       89900              Toronto, Ontario  14-04-2020   
32564     44949       89901                          OHIO  14-04-2020   
32565     44951       89903  Wellington City, New Zealand  14-04-2020   
32566     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet Sentiment  
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral  
1      advice Talk to your neighbours family to excha...  Positive  
2      Coronavirus Australia: Woolworths to give elde...  Positive  
3      As news of the region’s first confirmed COVID...  Positive  
4      Cashier at grocery store was sharing his insig...  Positive  
...                                                  ...       ...  
32562  Y’all really shitting that much more at home?...  Negative  
32563  Still shocked by the number of #Toronto superm...  Negative  
32564  I never that we’d be in a situation &amp; wor...  Positive  
32565  Airline pilots offering to stock supermarket s...   Neutral  
32566  @TartiiCat Well new/used Rift S are going for ...  Negative  

[32567 rows x 6 columns]

In [79]:
df = pd.concat([df, pd.DataFrame(res, columns=["CleanedTweet"])], axis=1, sort=False)

In [80]:
df

UserName  ScreenName                      Location     TweetAt  \
0          3799       48751                        London  16-03-2020   
1          3800       48752                            UK  16-03-2020   
2          3801       48753                     Vagabonds  16-03-2020   
3          3804       48756     ÜT: 36.319708,-82.363649  16-03-2020   
4          3805       48757          35.926541,-78.753267  16-03-2020   
...         ...         ...                           ...         ...   
32562     44946       89898                  Brooklyn, NY  14-04-2020   
32563     44948       89900              Toronto, Ontario  14-04-2020   
32564     44949       89901                          OHIO  14-04-2020   
32565     44951       89903  Wellington City, New Zealand  14-04-2020   
32566     44955       89907  i love you so much || he/him  14-04-2020   

                                           OriginalTweet Sentiment  \
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral   
1      advice Talk to your neighbours family to excha...  Positive   
2      Coronavirus Australia: Woolworths to give elde...  Positive   
3      As news of the region’s first confirmed COVID...  Positive   
4      Cashier at grocery store was sharing his insig...  Positive   
...                                                  ...       ...   
32562  Y’all really shitting that much more at home?...  Negative   
32563  Still shocked by the number of #Toronto superm...  Negative   
32564  I never that we’d be in a situation &amp; wor...  Positive   
32565  Airline pilots offering to stock supermarket s...   Neutral   
32566  @TartiiCat Well new/used Rift S are going for ...  Negative   

                                            CleanedTweet  
0      gahan http co ifz9fan2pa http co xx6ghgfzcc ht...  
1      advice talk neighbour family exchange phone nu...  
2      coronavirus australia woolworth give elderly d...  
3      news region first confirmed covid 19 case came...  
4      cashier grocery store sharing insight 19 prove...  
...                                                  ...  
32562                          really shitting much home  
32563  still shocked number supermarket employee work...  
32564  never situation amp world going supermarket pi...  
32565  airline pilot offering stock supermarket shelf...  
32566  well new used rift going 700 00 amazon rn alth...  

[32567 rows x 7 columns]

In [81]:
X = df['CleanedTweet']
Y = df['Sentiment']
print(X.shape, Y.shape)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)


(32567,) (32567,)


In [82]:
print(X_train.shape, Y_train.shape)

(22796,) (22796,)


In [83]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(max_features=1500)
X_train_counts = count_vect.fit_transform(X_train)


In [84]:
X_train_counts.shape

(22796, 1500)

In [85]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [86]:
print(X_train_tfidf.shape)
Y_train.shape

(22796, 1500)


(22796,)

In [87]:
count_vect = CountVectorizer(max_features=1500)
X_test_counts = count_vect.fit_transform(X_test)
tfidf_transformer = TfidfTransformer()
X_test_tfidf = tfidf_transformer.fit_transform(X_test_counts)

SVM Classification

In [88]:
from sklearn.svm import SVC
clf = SVC(gamma = 'auto', kernel = 'linear')
clf.fit(X_train_tfidf, Y_train)


SVC(gamma='auto', kernel='linear')

In [89]:
clf.score(X_train_tfidf, Y_train)


0.8122477627653975

In [90]:
Ypred_clf = clf.predict(X_test_tfidf)


In [91]:
Ypred_clf

array(['Positive', 'Neutral', 'Negative', ..., 'Positive', 'Positive',
       'Negative'], dtype=object)

Compute Confusion matrix and classification report 

In [92]:
cm_clf = confusion_matrix(Y_test, Ypred_clf)
print(cm_clf)
print(classification_report(Y_test, Ypred_clf))

[[1795  307 1495]
 [ 583  462  798]
 [1514  424 2393]]
              precision    recall  f1-score   support

    Negative       0.46      0.50      0.48      3597
     Neutral       0.39      0.25      0.30      1843
    Positive       0.51      0.55      0.53      4331

    accuracy                           0.48      9771
   macro avg       0.45      0.43      0.44      9771
weighted avg       0.47      0.48      0.47      9771



KNN Classification

In [93]:
from sklearn.neighbors import KNeighborsClassifier

In [94]:
knn = KNeighborsClassifier(n_neighbors=200)
knn.fit(X_train_tfidf, Y_train)

KNeighborsClassifier(n_neighbors=200)

In [95]:
knn.score(X_train_tfidf,Y_train)

0.6192314441130022

In [96]:
Ypred_knn = knn.predict(X_test_tfidf)
Ypred_knn

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Neutral'], dtype=object)

Confusion matrix and classification report

In [97]:
cm_knn = confusion_matrix(Y_test, Ypred_knn)
print(cm_knn)
print(classification_report(Y_test, Ypred_knn))

[[1525  216 1856]
 [ 483  225 1135]
 [1136  288 2907]]
              precision    recall  f1-score   support

    Negative       0.49      0.42      0.45      3597
     Neutral       0.31      0.12      0.17      1843
    Positive       0.49      0.67      0.57      4331

    accuracy                           0.48      9771
   macro avg       0.43      0.41      0.40      9771
weighted avg       0.46      0.48      0.45      9771



SVM CLASSIFICATION GIVES THE BEST ACCURACY